package ExceptionHandlingDay6;

public class ExceptionDemo3 {

	public static void main(String[] args) {
		
		System.out.println("Program task begins");
		try {
			int c=10/0;
			System.out.println("From Try..");
			
		}catch(Exception e) {
			System.out.println("From Catch..");
		}
		finally {
			System.out.println("From Finally..");
		}
		System.out.println("Program Completed Task");
	}

}
