package ExceptionHandlingDay6;

public class ExceptionDemo3 {

	public static void main(String[] args) {
		
		System.out.println("Program task begins");
		try {
			System.out.println("From try..");
			
		}catch(Exception e) {
			System.out.println("From Catch..");
		}
		finally {
			System.out.println("From finally");
		}
		System.out.println("Program Completed Task");
	}

}
